apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference only existing files
resources:
- image-update.yaml

# Common metadata for all apps
commonLabels:
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: "{{APP_NAME}}"

# Image pull secret configuration
secretGenerator:
- name: ghcr-secret
  behavior: merge
  literals:
  - .dockerconfigjson={"auths":{"ghcr.io":{"auth":"$(echo -n $GHCR_USER:$GHCR_PAT | base64)"}}}
  type: kubernetes.io/dockerconfigjson