apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gotk-components.yaml
- gotk-sync.yaml

# Reference template as a component
components:
- ../../apps/_template

# Configure Flux components
patchesStrategicMerge:
- patch-image-automation.yaml