apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: flux-image-automation
        email: flux@your-org.com
      messageTemplate: |
        Update image for {{ .ResourcePath }}
        [ci skip]
    push:
      branch: main
  update:
    path: ./workloads
    strategy: Setters