apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-cicd
spec:
  template:
    spec:
      containers:
      - name: demo-cicd
        image: ghcr.io/shahryaraly/demo-cicd:1.0.0 # Auto-updated
      imagePullSecrets:
      - name: ghcr-secret