apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cluster-level resources
resources:
- flux-system/gotk-components.yaml
- flux-system/gotk-sync.yaml
- apps/demo-cicd

# Application components
# components:
# - apps/

# Apply to all namespaces
namespace: flux-system

# Configure image automation
# patchesStrategicMerge:
# - flux-system/patch-image-automation.yaml