apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: demo-cicd
spec:
  image: ghcr.io/shahryaraly/demo-cicd
  interval: 1m

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: demo-cicd
spec:
  imageRepositoryRef:
    name: demo-cicd
  policy:
    semver:
      range: ">=1.0.0"

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: demo-cicd
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    commit:
      author:
        name: flux-bot
        email: flux@your-org.com
    push:
      branch: main
  update:
    path: ./generated/workloads/demo-cicd
    strategy: Setters