apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference only existing files
resources:
- image-update.yaml

# Common metadata for all apps
commonLabels:
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: "demo-cicd"

# Image pull secret configuration
secretGenerator:
- name: ghcr-secret
  behavior: merge
  literals:
  - .dockerconfigjson={"auths":{"ghcr.io":{"auth":"$(echo -n $GHCR_USER:$GHCR_PAT | base64)"}}}
  type: kubernetes.io/dockerconfigjson

# Add image automation components directly
patches:
- target:
    kind: ImageUpdateAutomation
    name: "demo-cicd"
  patch: |
    - op: add
      path: /spec/git
      value:
        checkout:
          ref:
            branch: main
        commit:
          author:
            name: flux-bot
            email: flux@your-org.com
        push:
          branch: main