name: Build and Push

on:
  push:
    branches: [ "main" ]
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        id: vars
        run: |
          # Get the app name from the repository name
          echo "APP_NAME=$(basename '${{ github.repository }}')" >> "$GITHUB_OUTPUT"

      - name: Checkout App Repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          APP_NAME=${{ steps.vars.outputs.APP_NAME }}
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$APP_NAME:${{ github.sha }}

          echo "Building $IMAGE_NAME"
          docker build -t $IMAGE_NAME
          docker push $IMAGE_NAME