
name: Build and Push
on:
  push:
    branches: [ "main" ]
    paths:
      - '**'  # Watch all paths in THIS repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: shahryaraly/project-rc-infra  # Change to your actual app repo
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/YOUR_APP_NAME:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/YOUR_APP_NAME:${{ github.sha }}