name: Build and Push

on:
  push:
    branches: [ "main" ]
    paths:
      - '**'
  workflow_dispatch:   # Add this line to allow manual/API trigger!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        id: vars
        run: |
          echo "APP_NAME=$(basename '${{ github.repository }}')" >> "$GITHUB_OUTPUT"

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          APP_NAME=${{ steps.vars.outputs.APP_NAME }}
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$APP_NAME:${{ github.sha }}

          echo "Building $IMAGE_NAME"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
