name: Build and Push

on:
  push:
    branches: [ "main" ]
    paths:
      - '**'
  workflow_dispatch:   # Add this line to allow manual/API trigger!
    inputs:
      application_repo:
        description: 'Repository to build (format: owner/repo)'
        required: true
        type: string
      dockerfile_path:
        description: 'Path to Dockerfile in the application repo'
        required: false
        type: string
        default: "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          APP_NAME=${{ inputs.application_repo }}
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$APP_NAME:${{ github.sha }}

          echo "Building $IMAGE_NAME from ${{ inputs.dockerfile_path }}"
          docker build -t $IMAGE_NAME -f ${{ inputs.dockerfile_path }} .
          docker push $IMAGE_NAME
