name: Deploy
on:
  workflow_run:
    workflows: ["Build and Push"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: shahryaraly/project-rc-infra
          path: app

      - name: Deploy
        run: |
          kubectl apply -f app/k8s/
          kubectl set image deployment/YOUR_DEPLOYMENT_NAME YOUR_CONTAINER_NAME=ghcr.io/${{ github.repository_owner }}/YOUR_APP_NAME:${{ github.event.workflow_run.head_sha }}
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}